# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_message',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
