# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0003_datepostmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datepost',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataposts', to='apiserver.Couple'),
        ),
        migrations.AlterField(
            model_name='datepostcomment',
            name='datepost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datepostcomments', to='apiserver.DatePost'),
        ),
        migrations.AlterField(
            model_name='datepostcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datepostcomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datepostmedia',
            name='datepost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datepostmedias', to='apiserver.DatePost'),
        ),
        migrations.AlterField(
            model_name='user',
            name='couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='apiserver.Couple'),
        ),
    ]
