# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0006_auto_20160223_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='coupling_begin',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
    ]
